project-axf/axf/urls.py
# -*- coding: utf-8 -*-
__author__ = 'QB'

from django.conf.urls import url
from axf import views
urlpatterns = [
    # 首页
    url(r'^home/$', views.home, name='home'),

    # 个人中心
    url(r'^mine/$', views.mine, name='mine'),

    # 闪购超市
    url(r'^market/$', views.market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.user_market, name='market_params'),

    # 添加购物车
    url(r'^addCart/', views.add_cart, name='addCart'),
    url(r'^subCart/', views.sub_cart, name='subCart'),

    # 购物车页面
    url(r'^cart/$', views.cart, name='cart'),

    # 修改购物车中商品的选择情况
    url(r'^changeSelectStatus/', views.change_select_status, name='change_select_status'),

    # 下单
    url(r'^generateOrder/', views.generate_order, name='generate_order'),

    # 修改订单状态
    url(r'^changeOrderStatus/', views.change_order_status, name='change_order_status'),

    # 代付款订单
    url(r'^waitPay/', views.order_wait_pay, name='order_wait_pay'),

    # 待收货
    url(r'^payed/', views.order_payed, name='order_payed'),

    # 代付款订单支付
    url(r'^waitPayToPayed/', views.wait_pay_to_payed, name='wait_pay_to_payed'),

    # 全选
    url(r'^changeCartAllSelect/', views.change_cart_all_select, name='change_cart_all_select'),

    # 总价
    url(r'^countPrice/', views.count_price, name='count_price'),
]

project-axf/projectaxf/urls.py
'''
全局路由配置
'''
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    # host/admin/...   访问django默认站点管理页面
    url(r'^admin/', admin.site.urls),

    # host/axf/...     交由axf.urls进行处理
    url(r'^axf/', include('axf.urls', namespace='axf')),

    # host/    主页的访问交由views.home函数处理
    url(r'^user/', include('user.urls', namespace='user')),

]

project-axf/user/urls.py
# -*- coding: utf-8 -*-
__author__ = 'QB'
from django.conf.urls import url
from user import views

urlpatterns = [
    # 登录
    url(r'^login/$', views.login, name='login'),
    # 注册
    url(r'^register/$', views.register, name='register'),
    # 注销
    url(r'^logout/$', views.logout, name='logout'),
    # 检查用户名是否已经存在
    url(r'^checkuser/', views.check_user, name='check_user'),
]

project-axf/axf/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.core.urlresolvers import reverse

from axf.models import MainWheel, MainNav, MainMustBuy, \
    MainShop, MainShow, FoodType, Goods, CartModel, \
    OrderModel, OrderGoodsModel

from user.models import UserTicketModel
from utils.functions import get_order_random_id


def home(request):
    """
    首页视图函数
    """
    if request.method == 'GET':
        # 查询数据
        mainwheels = MainWheel.objects.all()
        mainnavs = MainNav.objects.all()
        mainbuys = MainMustBuy.objects.all()
        mainshops = MainShop.objects.all()
        mainshows = MainShow.objects.all()

        # 组织数据
        data = {
            'title': '首页',
            'mainwheels': mainwheels,
            'mainnavs': mainnavs,
            'mainbuys': mainbuys,
            'mainshops': mainshops,
            'mainshows': mainshows,
        }
        # 携带数据渲染页面
        return render(request, 'axf/home.html', data)


def mine(request):
    """
    我的
    """
    if request.method == 'GET':
        user = request.user
        orders = OrderModel.objects.filter(user=user)
        payed, wait_pay = 0, 0
        for order in orders:
            if order.o_status == 0:
                wait_pay += 1
            if order.o_status == 1:
                payed += 1
        data = {
            "title": "我的",
            'wait_pay': wait_pay,
            'payed': payed
        }
    return render(request, 'axf/mine.html', data)


def market(request):
    """
    闪购超市
    """
    if request.method == 'GET':
        # 重定向到market_params方法所对应的路由
        return HttpResponseRedirect(reverse('axf:market_params', args=('104749', '0', '0')))


def user_market(request, typeid, cid, sid):
    """
    闪购详情
    :param request:
    :param typeid: 分类id
    :param cid: 子类id
    :param sid: 排序id
    """
    if request.method == 'GET':
        ticket = request.COOKIES.get('ticket')
        user_ticket = UserTicketModel.objects.filter(ticket=ticket).first()
        if user_ticket:
            user = user_ticket.user
        else:
            user = ''
        # 查询所有食品类型
        foodtypes = FoodType.objects.all()
        # 根据分类查询到对应的所有商品
        if cid == '0':
            goods = Goods.objects.filter(categoryid=typeid)
        # typeid 和 categoryid   并且是一对多的一个关系
        else:
            goods = Goods.objects.filter(categoryid=typeid, childcid=cid)

        # 重新组装全部分类的参数
        # 组装结果为[['全部分类','0'], ['酒类':13550], ['饮用水':15431]]
        foodtypes_current = foodtypes.filter(typeid=typeid).first()
        if foodtypes_current:
            childtypes = foodtypes_current.childtypenames
            childtypenames = childtypes.split('#')
            child_list = []
            for childtypename in childtypenames:
                child_type_info = childtypename.split(':')
                child_list.append(child_type_info)

        # 将商品按指定顺序排序
        if sid == '0':
            pass
        if sid == '1':
            goods = goods.order_by('productnum')
        if sid == '2':
            goods = goods.order_by('price')
        if sid == '3':
            goods = goods.order_by('-price')

        # 返回购物车信息
        if user:
            user_cart = CartModel.objects.filter(user=user)
        else:
            user_cart = ''

        # 当前选择的商品数量
        for g in goods:
            for c in user_cart:
                if c.goods.id == g.id:
                    g.num = c.c_num

        # 组织数据
        data = {
            "title": "闪送超市",
            'foodtypes': foodtypes,
            'goods': goods,
            'typeid': typeid,
            'child_list': child_list,
            'cid': cid,
            'user_cart': user_cart
        }
        # 传递数据给页面并渲染
        return render(request, 'axf/market.html', data)


def add_cart(request):
    """
    添加商品到购物车
    """
    if request.method == 'POST':
        # 获取当前用户
        user = request.user
        # 获取前端 POST 的当前商品 ID
        goods_id = request.POST.get('goods_id')
        good = Goods.objects.get(id=goods_id)
        # 定义返回 Json 格式
        data = {
            'code': 200,
            'msg': '请求成功'
        }
        # 判断当前是系统自带的还是登录用户
        if user.id:
            if good.storenums == 0:
                data['code'] = 900
                data['msg'] = '库存不足'
                return JsonResponse(data)
            # 是登录用户就根据商品 ID 和用户获取一个购物车对象
            user_cart = CartModel.objects.filter(user=user, goods_id=goods_id).first()

            # 判断是否有购物车对象
            if user_cart:
                # 有的话商品数量 +1
                user_cart.c_num += 1
                # 保存进数据库
                user_cart.save()
                # 插入返回 json 数据
                data['c_num'] = user_cart.c_num
            else:
                # 没有购物车对象，则进行创建
                CartModel.objects.create(user=user, goods_id=goods_id)
                data['c_num'] = 1
            # 库存 -1
            good.storenums -= 1
            good.save()
            return JsonResponse(data)
        data['code'] = 403
        data['msg'] = '请先登录'
        return JsonResponse(data)


def sub_cart(request):
    """
    减少购物车用户下单商品的数量
    """
    data = {
        'code': 200,
        'msg': '请求成功'
    }
    if request.method == 'POST':
        user = request.user
        goods_id = request.POST.get('goods_id')
        good = Goods.objects.get(id=goods_id)
        if user.id:
            # 获取用户下单对应的商品信息
            user_cart = CartModel.objects.filter(user=user, goods_id=goods_id).first()
            # 判断购物车有无此商品数据
            if user_cart:
                # 如果购物车商品只剩下最后一个
                if user_cart.c_num == 1:
                    # 删除当前商品所有信息
                    user_cart.delete()
                    # 商品数量重置为 0
                    data['c_num'] = 0
                else:
                    # 商品数量大于一个就减一
                    user_cart.c_num -= 1
                    # 保存数据到数据库
                    user_cart.save()
                    # 把减少后的商品数量添加到返回数据
                    data['c_num'] = user_cart.c_num
                # 库存 +1
                good.storenums += 1
                good.save()
                # 返回数据
                return JsonResponse(data)

        data['code'] = 403
        data['msg'] = '请先登录'
        return JsonResponse(data)


def cart(request):
    """
    购物车
    """
    if request.method == 'GET':
        # 获取用户
        user = request.user
        # 查询购物车信息
        user_carts = CartModel.objects.filter(user=user)

        data = {
            "title": "购物车",
            'user_carts': user_carts
        }
        return render(request, 'axf/cart.html', data)


def change_select_status(request):
    if request.method == 'POST':
        cart_id = request.POST.get('cart_id')
        cart = CartModel.objects.filter(id=cart_id).first()
        if cart.is_select:
            cart.is_select = False
        else:
            cart.is_select = True
        cart.save()

        data = {
            'code': 200,
            'msg': '请求成功',
            'is_select': cart.is_select
        }
        return JsonResponse(data)


def generate_order(request):
    """
    下单
    """
    if request.method == 'GET':
        user = request.user
        # 创建订单
        o_num = get_order_random_id()
        order = OrderModel.objects.create(user=user, o_num=o_num)
        # 选择勾选的商品进行下单
        user_carts = CartModel.objects.filter(user=user, is_select=True)
        for carts in user_carts:
            # 创建商品和订单之间的关系
            OrderGoodsModel.objects.create(goods=carts.goods,
                                           order=order,
                                           goods_num=carts.c_num)
        user_carts.delete()

        return render(request, 'order/order_info.html', {'order': order})


def change_order_status(request):
    """
    修改订单状态
    """
    if request.method == 'POST':
        order_id = request.POST.get('order_id')
        OrderModel.objects.filter(id=order_id).update(o_status=1)
        data = {'code': 200, 'msg': '请求成功'}
        return JsonResponse(data)


def order_wait_pay(request):
    """
    代付款 ，o_status=0
    """
    if request.method == 'GET':
        user = request.user
        orders = OrderModel.objects.filter(user=user, o_status=0)
        data = {'orders': orders}
        return render(request, 'order/order_list_wait_pay.html', data)


def order_payed(request):
    """
    待收货 o_status=1
    """
    if request.method == 'GET':
        user = request.user
        orders = OrderModel.objects.filter(user=user, o_status=1)
        data = {'orders': orders}
        return render(request, 'order/order_list_payed.html', data)


def wait_pay_to_payed(request):
    """
    代付款订单跳转到付款页面
    """
    if request.method == 'GET':
        order_id = request.GET.get('order_id')
        order = OrderModel.objects.filter(id=order_id).first()
        data = {'orders': order}
        return render(request, 'order/order_info.html', data)


def change_cart_all_select(request):
    if request.method == 'POST':
        user = request.user
        is_select = request.POST.get('all_select')
        flag = False
        user_carts = CartModel.objects.filter(user=user)
        if is_select == '1':
            CartModel.objects.filter(user=user).update(is_select=True)
        else:
            flag = True
            CartModel.objects.filter(user=user).update(is_select=False)

        data = {
            'code': 200,
            'ids': [u.id for u in user_carts],
            'flag': flag
        }
        return JsonResponse(data)


def count_price(request):
    if request.method == 'GET':

        user = request.user
        user_carts = CartModel.objects.filter(user=user, is_select=True)
        price = 0

        for carts in user_carts:
            price += carts.goods.price * carts.c_num
        data = {
            'code': 200,
            'count_price': round(price, 3),
            'msg': '请求成功'
        }
        return JsonResponse(data)

project-axf/templates/axf/cart.html
{% extends 'base_main.html' %}

{% load static %}
{#{% load static from staticfiles %}#}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'axf/cart/cart.css' %}"/>
{% endblock %}

{% block EXTJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/cart/js/cart.js' %}"></script>
    <script type="text/javascript" src="{% static 'axf/common/functions.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="cart">

        <h3>购物车</h3>

        <section class="full">
            <section class="clear">

                <ul>
                    <li>
                        <div class="clear">
                            <p class="infoJustify">收货人<b></b></p> : <span>大蟀蟀</span>
                        </div>
                    </li>
                    <li>
                        <div class="clear">
                            <p class="infoJustify">电话<b></b></p> : <span>020-00008888</span>
                            <a href="#" class="change">修改&gt;</a>
                        </div>
                    </li>
                    <li>
                        <div class="clear">
                            <p class="infoJustify">收货地址<b></b></p> : <span>XX 室 XX 号 XX 弄 XX 路</span>
                        </div>
                    </li>
                </ul>

                <section class="bill">
                    <p>闪送超市</p>
                    <a href="#">凑单专区</a>
                    <p>满100减99</p>
                </section>

                <section class="delivery">
                    <span>收货时间:</span>
                    <span>一小时送达</span>
                    <a href="#">可预定&gt;</a>
                </section>

                <section class="delivery">
                    <span>收货备注:</span>
                    <input type="text" placeholder="可输入100字以内特殊需求内容">
                </section>

                <menu>
                    <ul>
                        <!--购物车信息展示-->
                        {% csrf_token %}
                        {% for cart in user_carts %}
                            <li class="menuList" cartid="{{ cart.id }}">
                                <div class="confirm">
                                    <span class="is_choose" id="changeselect_{{ cart.id }}">
                                        {% if cart.is_select %}
                                            <span id="cart_id_{{ cart.id }}"
                                                  onclick="changeSelectStatus({{ cart.id }});"
                                            >
                                                √
                                            </span>
                                        {% else %}
                                            <span id="cart_id_{{ cart.id }}"
                                                  onclick="changeSelectStatus({{ cart.id }});"
                                            >
                                                x
                                            </span>
                                        {% endif %}
                                    </span>
                                </div>
                                <a href="javascript:;">
                                    <img src="{{ cart.goods.productimg }}" alt="{{cart.goods.productname}}">
                                    <p>{{ cart.goods.productlongname }}</p>
                                    <span>¥{{ cart.goods.price }}</span>
                                    <s>¥{{ cart.goods.marketprice }}</s>
                                </a>
                                <section>
                                    <button onclick="subCart({{ cart.goods.id }})">-</button>
                                    <span id="num_{{ cart.goods.id }}">{{ cart.c_num }}</span>
                                    <button onclick="addCart({{ cart.goods.id }})">+</button>
                                </section>
                            </li>
                        {% endfor %}
                        <!--购物车数据处理结束-->
                        <li class="payTheBill">

                            <div class="confirm" onclick="all_select(1)" id="all_select_id">
                                <span>
                                    <span id="select_id">√</span>
                                </span>
                            </div>

                            <p>
                                <span>全选</span>
                                <span id="count_price">总价:</span>
                            </p>
                            <span><a href="{% url 'axf:generate_order' %}">下单</a></span>
                        </li>
                    </ul>
                </menu>

            </section>
        </section>
    </div>
{% endblock %}

project-axf/templates/axf/home.html
{# 继承父类页面 #}
{% extends 'base_main.html' %}

{# 加载静态资源:CSS,JS,图片等，以下两种方式 #}
{% load static %}
{#{% load static from staticfiles %}#}

{# 继承并填充父类内容 #}
{% block extCSS %}
    {{ block.super }}
    {# 引入外部css样式 #}
    <link rel="stylesheet" href="{% static 'axf/home/home.css' %}">
{% endblock %}

{# 引入外部js脚本 #}
{% block EXTJS %}
    <script type="text/javascript" src="{% static 'axf/home/js/home.js' %}"></script>
{% endblock %}

{# 填充内容 #}
{% block content %}

    <div id="home">
        {#  顶部轮播  #}
        <section class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">
                <!--处理轮播banner图-->
                {% for wheel in mainwheels %}
                    <div class="swiper-slide">
                        <a href="#">
                            <img src="{{ wheel.img }}" alt="">
                        </a>
                    </div>
                {% endfor %}
                <!-- 处理结束 -->
            </div>
            <!-- 如果需要分页器 小圆点 -->
            <div class="swiper-pagination"></div>
        </section>

        {#  导航  #}
        <div class="topMenu">
            <nav>
                <ul>
                    <!-- 处理导航数据 -->
                    {% for nav in mainnavs %}
                        <li>
                            <a href="#">
                                <img src="{{ nav.img }}" />
                                <span>{{ nav.name }}</span>
                            </a>
                        </li>
                    {% endfor %}
                    <!--处理结束-->
                </ul>
            </nav>
        </div>
        {# 必购 #}
        <div id="swiperMenu" class="swiper-container">
            <ul class="swiper-wrapper">
                <!-- 处理必购商品信息 -->
                {% for buys in mainbuys %}
                    <li class="swiper-slide">
                        <a href="#"><img src="{{ buys.img }}" /></a>
                    </li>
                {% endfor %}
                <!-- 处理结束 -->
            </ul>
        </div>

        {#  便利店  #}
        <div class="CVS">
            <!--处理第一个店铺的数据的图片-->
            {% for shops in mainshops %}
                {% ifequal forloop.counter 1 %}
                    <h2>
                        <img src="{{ shops.img }}" />
                    </h2>
                {% endifequal %}
            {% endfor %}
            <!--处理结束-->

            <fieldset>
                {% for shops in mainshops %}
                    {% if forloop.counter > 1 and forloop.counter < 4 %}
                        <!--处理第二个到第四个数据-->
                        <a href="#">
                            <img src="{{ shops.img }}" />
                        </a>
                    {% endif %}
                    <!--处理结束-->
                {% endfor %}
            </fieldset>

            <ul>
                <!--处理第五个到第八个数据-->
                {% for shops in mainshops %}
                    {% if forloop.counter > 3 and forloop.counter < 8 %}
                        <li>
                            <a href="#">
                                <img src="{{ shops.img }}" />
                                <span>{{ shops.name }}</span>
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}
                <!--处理结束-->
            </ul>

            <ol>
                <!--处理第八个到第十二个数据-->
                {% for shops in mainshops %}
                    {% if forloop.counter > 7 and forloop.counter < 12 %}
                        <li>
                            <a href="#">
                                <img src="{{ shops.img }}" />
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}
                <!--处理结束-->
            </ol>
        </div>
        {#    主要显示    #}
        <div class="mainInfo">
            <!--商品展示-->
            {% for shows in mainshows %}
                <section>
                    <h3>
                        {{ shows.name }}
                        <a href="#">更多&gt;</a>
                        <span></span>
                    </h3>
                    <div>
                        <a href="#">
                            <img src="{{ shows.img }}" alt="{{ shows.name }}">
                        </a>
                    </div>
                    <ul>
                        <li>
                            <a href="#">
                                <img src="{{ shows.img1 }}" />
                                <p class="description">
                                    {{ shows.longname1 }}
                                </p>
                                <span>￥{{ shows.price1 }}</span>
                                <s>￥{{ shows.marketprice1 }}</s>
                            </a>
                            <button>
                                <span>+</span>
                            </button>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{{ shows.img2 }}" alt="{{ shows.longname2 }}">
                                <p class="description">
                                    {{ shows.longname2 }}
                                </p>
                                <span>￥{{ shows.price2 }}</span>
                                <s>￥{{ shows.marketprice2 }}</s>
                            </a>
                            <button>
                                <span>+</span>
                            </button>
                        </li>
                        <li>
                            <a href="#">
                                <img src="{{ shows.img3 }}" alt="{{ shows.longname3 }}">
                                <p class="description">
                                    {{ shows.longname3 }}
                                </p>
                                <span>￥{{ shows.price3 }}</span>
                                <s>￥{{ shows.marketprice3 }}</s>
                            </a>
                            <button>
                                <span>+</span>
                            </button>
                        </li>
                    </ul>
                </section>
            {% endfor %}
            <!--商品展示结束-->
        </div>
    </div>

{% endblock %}

project-axf/templates/axf/mine.html
{% extends 'base_main.html' %}

{% load static %}
{#{% load static from staticfiles %}#}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'axf/mine/mine.css' %}"/>
{% endblock %}

{% block EXTJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="mine">

        <div class="fixed">
            {# 如果登录，展示头像 #}
            {% if user.icon %}
                <img src="/static/uploads/{{ user.icon }}" alt="icon" />
            {# 或者 #}
            {% else %}
                <span class="glyphicon glyphicon-user"></span>
            {% endif %}
            {# 判断结束 #}

            {# 如果登录，展示姓名 #}
            {% if user.id %}
                <p>{{ user.username }}</p>
            {# 或者展示登录的链接 #}
            {% else %}
                <p><a href="{% url 'user:login' %}">请登录</a></p>
            {% endif %}
            {# 判断结束 #}

            <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>

            {# 如果没有登录,展示注册信息 #}
            {% if user.id %}
            {% else %}
                <div id="regis">
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
            {% endif %}
            {# 判断结束 #}

            <p><span class="glyphicon glyphicon-heart"></span><span>商品收藏</span></p>

        </div>

        <div class="mine">
            <p>我的订单<a href="#">更多&gt;</a></p>
            <div id="nav">
                <ul>
                    <li>
                        <dl>
                            <dt><span id="wait_pay_list" class="glyphicon glyphicon-usd"></span>
                                <span class="badge">
                                    {# 代付款的数量 #}
                                    {{ wait_pay }}
                                </span></dt>
                            <dd><a href="#">待付款</a></dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span id="order_payed_list" class="glyphicon glyphicon-envelope"></span>
                                <span class="badge">
                                    {# 待收货的数量 #}
                                    {{ payed }}
                                </span></dt>
                            <dd><a href="#">待收货</a></dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-retweet"></span></dt>
                            <dd>退款/售后</dd>
                        </dl>
                    </li>
                </ul>
            </div>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                            <span>积分商城</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                            <span>优惠券</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-import"></span></dt>
                            <span>收货地址</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                            <span>客户反馈</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-certificate"></span></dt>
                            <span>关于我们</span>
                        </dl>
                    </li>
                </ul>
            </menu>

            {# 如果登录了,则退出展示 #}
            {% if user.id %}
                <p class="logout">
                    <a href="{% url 'user:logout' %}">退出当前账号</a>
                </p>
            {% endif %}
            {# 判断结束 #}
        </div>
    </div>


{% endblock %}