project-template/myApp/urls.py
# -*- coding: utf-8 -*-
__author__ = 'QB'
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),  # http://127.0.0.1:8000

    url(r'^students/$', views.students),
    url(r'^good/(\d+)/$', views.good, name='good'),

    url(r'^main/$', views.main),
    url(r'^detail/$', views.detail),


    url(r'^posttest/$', views.posttest, name='showinfo'),
    url(r'^showinfo/$', views.showinfo, name='showinfo'),
    # 验证码
    url(r'^verifycode/$', views.verifycode, name='verifycode'),
    url(r'^verifyresult/$', views.verifyresult, name='verifyresult'),
    url(r'^verifycodecheck/$', views.verifycodecheck, name='verifycodecheck'),
]

project-template/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^qinbin/', include('myApp.urls', namespace="app"))
]

project-template/myApp/models.py
from django.db import models


# Create your models here.

class Grades(models.Model):
    # 不需要定义主键，在表生成时主键会自动添加，并且值为自动增加
    gname = models.CharField(max_length=20)
    gdate = models.DateTimeField()
    ggrilnum = models.IntegerField()
    gboynum = models.IntegerField()
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        # return "%s-%d-%d" % (self.gname, self.ggrilnum, self.gboynum)
        return self.gname

class Students(models.Model):
    sname = models.CharField(max_length=20)
    sgender = models.BooleanField(default=False)
    sage = models.IntegerField()
    scontent = models.CharField(max_length=30)
    isDelete = models.BooleanField(default=False)
    # 关联外键
    sgrade = models.ForeignKey("Grades")

    def __str__(self):
        return self.sname

    def getName(self):
        return self.sname

project-template/myApp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .models import Grades, Students


# 定义视图
def index(request):
    # return HttpResponse("my is a good man")
    student = Students.objects.get(pk=1)
    return render(request, 'myApp/index.html', {
        "stu": student,
        "list": ["qinbin", "qiuqiu", "dada"],
        "num": 10,
        "test": False,

    })


def students(request):
    studentsList = Students.objects.all()
    return render(request, 'myApp/students.html', {"students": studentsList})


def good(request, id):
    # http://127.0.0.1:8000/qinbin/good/13124/
    return render(request, 'myApp/good.html', {"id": id})


def main(request):
    # http://127.0.0.1:8000/qinbin/main/
    return render(request, 'myApp/main.html')


def detail(request):
    # http://127.0.0.1:8000/qinbin/detail/
    return render(request, 'myApp/detail.html')


def posttest(request):
    return render(request, 'myApp/posttest.html')


def showinfo(request):
    name = request.POST.get('username')
    pwd = request.POST.get('password')
    return render(request, 'myApp/showinfo.html', {
        "username": name,
        "password": pwd
    })


# 生成验证码
def verifycode(request):
    # 引入绘图模块
    from PIL import Image, ImageDraw, ImageFont
    # 引入随机函数模块
    import random
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), random.randrange(20, 100))
    width = 100
    height = 40
    # 创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的 point() 函数绘制噪点
    for i in range(0, 200):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = '0123456789aijklmbcfEFGHIJKLMghnoRSdeTUpqrstuvwxyzABCDNOPQVWXYZ'
    # 随机选取 4 个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    # 构造字体对象
    font = ImageFont.truetype('../fonts/msyhl.ttc', 25)
    # 构造字体颜色
    fontcolor1 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor2 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor3 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor4 = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制 4 个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor1)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor2)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor3)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor4)
    # 释放画笔
    del draw
    # 存入 session，用于做进一步验证
    request.session['verify'] = rand_str
    # 内存文件操作
    import io
    buf = io.BytesIO()
    # 将图片保存在内存中，文件类型为 png
    im.save(buf, 'png')
    # 将内存中的图片数据返回给客户端，MIME 类型为图片 png
    return HttpResponse(buf.getvalue(), 'image/png')


def verifyresult(request):
    return render(request,'myApp/verifyresult.html')


from django.http import HttpResponseRedirect
def verifycodecheck(request):
    code1 = request.POST.get("verifycode").upper()
    code2 = request.session["verify"].upper()
    if code1 == code2:
        return HttpResponse("<h1 style='color:green;'>验证成功！</h1>")
    return HttpResponse("<h1 style='color:red;'>验证失败！</h1>")

project-template/templates/myApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        #header{
            width: auto;
            height: 200px;
            background-color: #426c9e;
        }
        #footer{
            width: auto;
            height: 200px;
            background-color: greenyellow;
        }
    </style>

</head>
<body>
<div id="header">header</div>

<div id="main">
    {% block main %}
    {#    填充内容    #}
    {%endblock main %}

    {% block detail %}
    {#    填充内容    #}
    {%endblock detail %}
</div>

<div id="footer">footer</div>

</body>
</html>

project-template/templates/myApp/detail.html
{% extends 'myApp/base.html' %}

{% block main %}
    <h1>我是 detail，我来填 main 坑了。。。。</h1>
{% endblock main %}

{% block detail %}
    <h1>我是 detail，我来填 detail 坑了。。。。</h1>
{% endblock detail %}

project-template/templates/myApp/good.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Very Good!---{{ id }}</h1>
</body>
</html>

project-template/templates/myApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{# url 的反向解析 #}
<h1><a href="{% url 'app:good' 1 %}">good 链接</a></h1>

<h1>Bin Qin is good man</h1>
{# 1. 获取属性 #}
{#通过属性名获取学生名字#}
<h1>{{ stu.sname }}</h1>
{#通过自定义 get 方法获取#}
<h1>{{ stu.getName }}</h1>

{#  2. 注释的部分（多行注释）  #}
{% comment %}
    {% for stu in students %}
        <li>{{ forloop.counter }}——{{ stu.sname }}——{{ stu.sgrade }}</li>
    {% empty %}
        <li>目前没有学生</li>
    {% endfor %}
{% endcomment %}

{# 3. {% ifequal 'qinbin' 'qinbin' %} 的使用 #}
{% ifequal 'qinbin' 'qinbin' %}
    <h1>如果值1 与 值2 相等就输出，不相等就不输出！</h1>
{% endifequal %}

{# 4. 过滤器使用示例#}
<h1>{{ stu.sname|upper }}</h1>
<h1>{{ stu.sname }}</h1>

{# 5. join 的使用 #}
<h1>{{ list|join:'-' }}</h1>

{# 6. 默认值#}
<h1>{{ test|default:"None" }}</h1>

{# 7. 加减乘除#}
<h1>num = {{ num }}</h1>
<h1>num = {{ num|add:10 }}</h1>
<h1>num = {{ num|add:-5 }}</h1>
{# num/1*5 #}
{# num * 5 #}
<h1>num = {% widthratio num 1 5 %}</h1>
{# num / 5 #}
<h1>num = {% widthratio num 5 1 %}</h1>


</body>
</html>

project-template/templates/myApp/main.html
{% extends 'myApp/base.html' %}

{% block main %}
    <h1>我是 main，我来填 main 坑了。。。。</h1>
{% endblock main %}

project-template/templates/myApp/posttest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'app:showinfo' %}" method="post">
    姓名：<input type="text" name="username"><br>
    密码：<input type="password" name="password"><br>
    {% csrf_token %}
    <input type="submit" value="提交">
</form>
</body>
</html>

project-template/templates/myApp/showinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ username }}</h1>
<h1>{{ password }}</h1>
</body>
</html>

project-template/templates/myApp/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生列表</title>
</head>
<body>
<h1>学生列表</h1>
<ul>
    {#  1. for 循环  #}
    {% for stu in students %}
        {% if forloop.counter|divisibleby:2 %}
            <li style="color: green">
                {{ forloop.counter }}——{{ stu.sname }}——{{ stu.sgrade }}
            </li>
        {% else %}
            <li style="color: darkblue">
                {{ forloop.counter }}——{{ stu.sname }}——{{ stu.sgrade }}
            </li>
        {% endif %}
    {% empty %}
        <li>目前没有学生</li>
    {% endfor %}
</ul>


</body>
</html>

project-template/templates/myApp/verifyresult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'app:verifycodecheck' %}" method="post">
    <input type="text" name="verifycode">
    <a href="{% url 'app:verifyresult' %}"><img src="{% url 'app:verifycode' %}" alt="验证码"></a>
    {% csrf_token %}
    <input type="submit" name="提交验证">
</form>
</body>
</html>