project-axf/axf/urls.py
# -*- coding: utf-8 -*-
__author__ = 'QB'

from django.conf.urls import url
from axf import views
urlpatterns = [
    # 首页
    url(r'^home/$', views.home, name='home'),

    # 个人中心
    url(r'^mine/$', views.mine, name='mine'),

    # 闪购超市
    url(r'^market/$', views.market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.user_market, name='market_params'),

    # 添加购物车
    url(r'^addCart/', views.add_cart, name='addCart'),
    url(r'^subCart/', views.sub_cart, name='subCart'),

    # 购物车页面
    url(r'^cart/$', views.cart, name='cart'),

    # 修改购物车中商品的选择情况
    url(r'^changeSelectStatus/', views.change_select_status, name='change_select_status'),

    # 下单
    url(r'^generateOrder/', views.generate_order, name='generate_order'),

    # 修改订单状态
    url(r'^changeOrderStatus/', views.change_order_status, name='change_order_status'),

    # 代付款订单
    url(r'^waitPay/', views.order_wait_pay, name='order_wait_pay'),

    # 待收货
    url(r'^payed/', views.order_payed, name='order_payed'),

    # 代付款订单支付
    url(r'^waitPayToPayed/', views.wait_pay_to_payed, name='wait_pay_to_payed'),

    # 全选
    url(r'^changeCartAllSelect/', views.change_cart_all_select, name='change_cart_all_select'),

    # 总价
    url(r'^countPrice/', views.count_price, name='count_price'),
]

project-axf/projectaxf/urls.py
'''
全局路由配置
'''
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    # host/admin/...   访问django默认站点管理页面
    url(r'^admin/', admin.site.urls),

    # host/axf/...     交由axf.urls进行处理
    url(r'^axf/', include('axf.urls', namespace='axf')),

    # host/    主页的访问交由views.home函数处理
    url(r'^user/', include('user.urls', namespace='user')),

]

project-axf/templates/base.html
{# 加载静态资源 #}
{% load static %}

{# 页面内容 #}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {# TODO #}
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {# 引入全局样式，bootstrap，轮播框架 #}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">

    {# 挖坑：让子页面引入自己的样式 #}
    {% block extCSS %}

    {% endblock %}

    {# 接收并显示服务器传入的变量 #}
    <title>{{ title }}</title>
</head>
<body>

{# 挖坑让子类自行定义header #}
{% block header %}
{% endblock %}

{# 挖坑让子类自行定义内容 #}
{% block content %}
{% endblock %}

{# 挖坑让子类自行定义页脚 #}
{% block footer %}
{% endblock %}

{# 引入公共脚本:jq,bootstrap,全局脚本，轮播框架脚本 #}
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>

{# 挖坑让子类自行引入外部脚本 #}
{% block EXTJS %}
{% endblock %}

</body>
</html>

project-axf/templates/base_main.html
{# 继承父类页面 #}
{% extends 'base.html' %}

{# 加载静态资源 #}
{% load static %}

{# 引入外部样式 #}
{% block extCSS %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}

{# 填充统一的header #}
{% block header %}
    <header></header>
{% endblock %}

{# 填充统一的页脚 #}
{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt><span></span></dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'axf:market' %}" class="market">
            <dl>
                <dt><span></span></dt>
                <dd>闪购超市</dd>
            </dl>
        </a>
        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt><span></span></dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt><span></span></dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
{% endblock %}